name: ci
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out repo
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Setting node version
              shell: bash -l {0}
              run: nvm install
            - name: Installing dependencies
              run: yarn install --frozen-lockfile
            - name: Running tests
              run: yarn test
